export const CHANNELS = [
  {
    code: '0203',
    title: 'CCTV-1综合',
    channelNum: 999,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv1',
    channelNum: 1,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv2',
    channelNum: 2,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv3',
    channelNum: 3,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv4',
    channelNum: 4,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv5',
    channelNum: 5,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv6',
    channelNum: 6,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv7',
    channelNum: 7,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv8',
    channelNum: 8,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv9',
    channelNum: 9,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv10',
    channelNum: 10,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv11',
    channelNum: 11,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv12',
    channelNum: 12,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv13',
    channelNum: 13,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv14',
    channelNum: 14,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv15',
    channelNum: 15,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv16',
    channelNum: 16,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv17',
    channelNum: 17,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv18',
    channelNum: 18,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv19',
    channelNum: 19,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv20',
    channelNum: 20,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv21',
    channelNum: 21,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv22',
    channelNum: 22,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv23',
    channelNum: 23,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv24',
    channelNum: 24,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv25',
    channelNum: 25,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv26',
    channelNum: 26,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv27',
    channelNum: 27,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv28',
    channelNum: 28,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv29',
    channelNum: 29,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv30',
    channelNum: 30,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv31',
    channelNum: 31,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv32',
    channelNum: 32,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv33',
    channelNum: 33,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv34',
    channelNum: 34,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv35',
    channelNum: 35,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv36',
    channelNum: 36,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv37',
    channelNum: 37,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv38',
    channelNum: 38,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv39',
    channelNum: 39,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv40',
    channelNum: 40,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv41',
    channelNum: 41,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv42',
    channelNum: 42,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv43',
    channelNum: 43,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv44',
    channelNum: 44,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv45',
    channelNum: 45,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv46',
    channelNum: 46,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv47',
    channelNum: 47,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv48',
    channelNum: 48,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv49',
    channelNum: 49,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv50',
    channelNum: 50,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv51',
    channelNum: 51,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv52',
    channelNum: 52,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv53',
    channelNum: 53,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv54',
    channelNum: 54,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv55',
    channelNum: 55,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv56',
    channelNum: 56,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv57',
    channelNum: 57,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv58',
    channelNum: 58,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv59',
    channelNum: 59,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv60',
    channelNum: 60,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv61',
    channelNum: 61,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv62',
    channelNum: 62,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv63',
    channelNum: 63,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv64',
    channelNum: 64,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv65',
    channelNum: 65,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv66',
    channelNum: 66,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv67',
    channelNum: 67,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv68',
    channelNum: 68,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv69',
    channelNum: 69,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv70',
    channelNum: 70,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv71',
    channelNum: 71,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv72',
    channelNum: 72,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv73',
    channelNum: 73,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv74',
    channelNum: 74,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv75',
    channelNum: 75,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv76',
    channelNum: 76,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv77',
    channelNum: 77,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv78',
    channelNum: 78,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv79',
    channelNum: 79,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv80',
    channelNum: 80,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv81',
    channelNum: 81,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv82',
    channelNum: 82,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv83',
    channelNum: 83,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv84',
    channelNum: 84,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv85',
    channelNum: 85,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv86',
    channelNum: 86,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv87',
    channelNum: 87,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv88',
    channelNum: 88,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv89',
    channelNum: 89,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv90',
    channelNum: 90,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv91',
    channelNum: 91,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv92',
    channelNum: 92,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv93',
    channelNum: 93,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv94',
    channelNum: 94,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv95',
    channelNum: 95,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv96',
    channelNum: 96,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv97',
    channelNum: 97,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv98',
    channelNum: 98,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
  {
    code: '0203',
    title: 'tv99',
    channelNum: 99,
    icon: '',
    timeshiftAvailable: false,
    lookbackAvailable: false,
    isCharge: '0',
    params: {
      zeturl: 'rtp://localhost:3002',
      hwmediaid: '',
      ztecode: '0203',
      hwurl: 'rtp://localhost:3003',
      hwcode: '',
      recommendPos: 'BizPosition',
    },
  },
];
